//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MüsteriYönetimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kundenverwaltung
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Erstdatum { get; set; }
        public string Letztdatum { get; set; }
        public string Anschrift { get; set; }
        public int Betrag { get; set; }
        public string Handy { get; set; }
        public string Festnetz { get; set; }
        public string Objektart { get; set; }
        public string Material { get; set; }
        public Nullable<bool> Quittung { get; set; }
        public string Durch { get; set; }
        public string Bemerkung { get; set; }
    }
}
